name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  LLVM_VERSION: 19.1.4
  SCCACHE_DIRECT: yes

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            runner: ubuntu-latest
            cmake_args: -D CMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld
            line_continue: '\'

          - name: Windows
            runner: windows-latest
            cmake_args:
            line_continue: '`'

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        ref: llvmorg-${{ env.LLVM_VERSION }}
        path: third_party/llvm-project
        fetch-depth: 1

    - id: llvm-revision
      run: echo llvm_revision=$(git -C ${{ github.workspace }}/third_party/llvm-project rev-parse HEAD) >> ${GITHUB_ENV}

    - uses: hendrikmuhs/ccache-action@4cb35b2ff44ce57e1f5f5221e26bd8fefcfe41d0 # main as of 2024-01-21
      with:
        max-size: 10M
        key: ${{ runner.os }}-${{ env.llvm_revision }}
        variant: sccache

    - name: Configure LLVM
      run: >
        cmake -B ${{ github.workspace }}/build/llvm-project                     ${{ matrix.line_continue }}
              -D CMAKE_BUILD_TYPE=Release                                       ${{ matrix.line_continue }}
              -D CMAKE_C_COMPILER_LAUNCHER=sccache                              ${{ matrix.line_continue }}
              -D CMAKE_CXX_COMPILER_LAUNCHER=sccache                            ${{ matrix.line_continue }}
              -S ${{ github.workspace }}/third_party/llvm-project/llvm

    - name: Build LLVM
      run: >
        cmake --build ${{ github.workspace }}/build/llvm-project                ${{ matrix.line_continue }}
              --config Release                                                  ${{ matrix.line_continue }}
              --target FileCheck

    - if: runner.os == 'Linux'
      run: |
        curl -sL https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ env.LLVM_VERSION }}/LLVM-${{ env.LLVM_VERSION }}-Linux-X64.tar.xz -o ${{ github.workspace }}/third_party/LLVM-${{ env.LLVM_VERSION }}-Linux-X64.tar.xz
        tar Jxf ${{ github.workspace }}/third_party/LLVM-${{ env.LLVM_VERSION }}-Linux-X64.tar.xz -C ${{ github.workspace }}/third_party --strip-components 1

    - if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest -Uri "https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ env.LLVM_VERSION }}/clang+llvm-${{ env.LLVM_VERSION }}-x86_64-pc-windows-msvc.tar.xz" -OutFile "${{ github.workspace }}/third_party/clang+llvm-${{ env.LLVM_VERSION }}-x86_64-pc-windows-msvc.tar.xz"
        7z x "${{ github.workspace }}/third_party/clang+llvm-${{ env.LLVM_VERSION }}-x86_64-pc-windows-msvc.tar.xz" -o"${{ github.workspace }}/third_party"
        7z x "${{ github.workspace }}/third_party/clang+llvm-${{ env.LLVM_VERSION }}-x86_64-pc-windows-msvc.tar" -o"${{ github.workspace }}/third_party"
        Move-Item -Path "${{ github.workspace }}/third_party/clang+llvm-${{ env.LLVM_VERSION }}-x86_64-pc-windows-msvc/*" -Destination "${{ github.workspace }}/third_party" -Force

    - if: runner.os == 'Windows'
      run: |
        Get-ChildItem -Recurse "${{ github.workspace }}/third_party" | Format-List

    - if: runner.os == 'Windows'
      uses: compnerd/gha-setup-vsdevenv@v6
      with:
        components: "Microsoft.VisualStudio.Component.VC.Tools.x86.x64;Microsoft.VisualStudio.Workload.NativeDesktop"

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build                                  ${{ matrix.line_continue }}
              -D CMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}                         ${{ matrix.line_continue }}
              -D CMAKE_C_COMPILER=${{ github.workspace }}/third_party/bin/clang ${{ matrix.line_continue }}
              -D CMAKE_CXX_COMPILER=${{ github.workspace }}/third_party/bin/clang++ ${{ matrix.line_continue }}
              -D LLVM_DIR=${{ github.workspace }}/third_party/lib/cmake/llvm    ${{ matrix.line_continue }}
              -D Clang_DIR=${{ github.workspace }}/third_party/lib/cmake/clang  ${{ matrix.line_continue }}
              -D FILECHECK_EXECUTABLE=${{ github.workspace }}/build/llvm-project/bin/FileCheck ${{ matrix.line_continue }}
              -D LIT_EXECUTABLE=${{ github.workspace }}/third_party/llvm-project/llvm/utils/lit/lit.py ${{ matrix.line_continue }}
              ${{ matrix.cmake_args }}

    - name: Build
      run: >
        cmake --build ${{ github.workspace }}/build                             ${{ matrix.line_continue }}
              --config ${{ env.BUILD_TYPE }}

    - name: Test
      run: >
        cmake --build ${{github.workspace}}/build                               ${{ matrix.line_continue }}
              --target check-ids
